export const actions = {
  blog: {
    UPDATE_DETAILED_BLOG: "BLOG_UPDATE_DETAILED_BLOG",
    UPDATE_BLOG_LIST_PAGE: "BLOG_UPDATE_BLOG_LIST_PAGE"
  },
  jwt: {
    UPDATE_TOKEN_CREDENTIALS: "JWT_UPDATE_TOKEN_CREDENTIALS"
  }
};