export const ACTIONS = {
  BLOG: {
    UPDATE_DETAILED_BLOG: "BLOG_UPDATE_DETAILED_BLOG",
    UPDATE_BLOG_LIST_PAGE: "BLOG_UPDATE_BLOG_LIST_PAGE"
  },
  USER: {
    UPDATE_TOKEN_CREDENTIALS: "USER_UPDATE_TOKEN_CREDENTIALS",
    UPDATE_CURRENT_USER_DETAILS: "USER_UPDATE_CURRENT_USER_DETAILS"
  },
  MODAL: {
    SHOW_MODAL: "MODAL_SHOW",
    HIDE_MODAL: "MODAL_HIDE"
  }
};