apiVersion: v1
kind: ConfigMap
metadata:
  name: blogweb-react-config
data:
  env: |
    REACT_APP_BACKEND_URL=http://k8s-default-blogwebb-53dfd852b8-685377d2a0a8d394.elb.us-west-1.amazonaws.com
    REACT_APP_BACKEND_PORT=9000
    REACT_APP_BLOG_LIST_PAGE_SIZE=7
    REACT_APP_TOKEN_TTL_IN_MS=7200000
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: blogweb-backend-config
data:
  application-properties: |
    cors.allowedOrigins=*
    datasource.mysql.druid.username=admin
    datasource.mysql.druid.url=jdbc:mysql://mysql:3306/blog_web?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    redis.host=redis-master
    redis.port=6379
    jwt.validityInMs=3600000
