apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogweb-frontend-deployment
  labels:
    app: blogweb-react
    layer: frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: blogweb-react
      layer: frontend
  template:
    metadata:
      labels: 
        app: blogweb-react
        layer: frontend
    spec:
      containers:
      - name: blogweb-frontend
        image: ysjason/blogweb-frontend:prod
        imagePullPolicy: Always
        ports: 
        - containerPort: 3000
        volumeMounts:
        - name: env-config
          mountPath: /app/.env
          subPath: env
        resources:
          requests:	
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1.5"
      volumes:
        - name: env-config
          configMap:
            name: blogweb-react-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogweb-backend-deployment
  labels:
    app: blogweb-spring
    layer: backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: blogweb-spring
      layer: backend
  template:
    metadata:
      labels: 
        app: blogweb-spring
        layer: backend
    spec:
      containers:
      - name: blogweb-backend
        image: ysjason/blogweb-backend:prod
        imagePullPolicy: Always
        ports: 
        - containerPort: 9000
        resources:
          requests:	
            memory: "3Gi"
            cpu: "1"
          limits:
            memory: "3Gi"
            cpu: "1.5"
        volumeMounts:
        - name: app-config
          mountPath: /app/application-extra.properties
          subPath: application-properties
        env:
        - name: redis.password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: redisPassword
        - name: datasource.mysql.druid.password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
      volumes:
        - name: app-config
          configMap:
            name: blogweb-backend-config