apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  redisPassword: redis_G49!Zk4WK=Qv
  mysql-root-password: mysql_root_6Y@s
  mysql-replication-password: mysql_replica_s&cM
  mysql-password: mysql_admin_B7=x